
name: 'dbt_poc_postgre'
version: '0.1'
profile: 'dbt_poc_postgre'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  dbt_poc_postgre:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]
